import Foundation

/// Represents the type of equation being solved
enum EquationType: String, Codable, CaseIterable {
    case linear
    case quadratic
    case system
    case trigonometric
    case logarithmic
    case polynomial
    case derivative
    case integral
    case statistics
    case physics
}

/// User-selected difficulty level that affects problem complexity and explanation depth
enum Difficulty: String, Codable, CaseIterable {
    case beginner
    case intermediate
    case advanced
}

/// Game mode selection
enum GameMode: String, Codable, CaseIterable {
    case speedTrainer
    case battle
}

/// Mathematical operators in algebraic expressions
enum Operator: String, Codable, CaseIterable {
    case add = "+"
    case subtract = "-"
    case multiply = "*"
    case divide = "/"
    case power = "^"
    
    var precedence: Int {
        switch self {
        case .add, .subtract:
            return 1
        case .multiply, .divide:
            return 2
        case .power:
            return 3
        }
    }
}

/// Unary operators (prefix operations)
enum UnaryOperator: String, Codable {
    case negate = "-"
}

/// Themes for real-life word problems
enum WordProblemTheme: String, CaseIterable {
    case shopping
    case distance
    case cooking
    case sports
    case money
    
    var context: String {
        switch self {
        case .shopping:
            return "buying items"
        case .distance:
            return "traveling or measuring"
        case .cooking:
            return "ingredients or portions"
        case .sports:
            return "points or distances"
        case .money:
            return "earning or spending"
        }
    }
}

/// Parse errors that can occur during equation parsing
enum ParseError: LocalizedError {
    case emptyInput
    case noEqualsSign
    case multipleEqualsSign
    case invalidToken(position: Int, character: Character)
    case unexpectedEndOfInput
    case unmatchedParenthesis
    case invalidNumber(String)
    case invalidVariable(String)
    
    var errorDescription: String? {
        switch self {
        case .emptyInput:
            return "Please enter an equation"
        case .noEqualsSign:
            return "Equation must contain exactly one '=' sign"
        case .multipleEqualsSign:
            return "Equation can only have one '=' sign"
        case .invalidToken(let pos, let char):
            return "Invalid character '\(char)' at position \(pos)"
        case .unexpectedEndOfInput:
            return "Equation is incomplete"
        case .unmatchedParenthesis:
            return "Parentheses don't match"
        case .invalidNumber(let text):
            return "'\(text)' is not a valid number"
        case .invalidVariable(let name):
            return "'\(name)' is not a valid variable"
        }
    }
}

/// Points on a graph that have special significance
enum GraphPointType: String, Codable {
    case xIntercept
    case yIntercept
    case intersection
    case vertex
}

/// How an equation was entered into the system
enum InputSource: String, Codable, CaseIterable {
    /// User manually typed the equation
    case manual
    /// Equation was captured via camera scan
    case camera
}

/// Source of an explanation
enum ExplanationSource: String, Codable, CaseIterable {
    /// Generated by the Google Gemini API
    case ai
    /// Generated from built-in template explainers
    case template
}

/// Calculus operation mode
enum CalculusMode: String, CaseIterable {
    case limits = "Limits"
    case derivatives = "Derivatives"
    case integrals = "Integrals"
}

/// Identifies which Calculus input field is currently focused
/// Determines which custom keyboard to display
enum CalculusFieldType: Hashable {
    case expression
    case variable
    case approachValue
    case lowerBound
    case upperBound
}
